- name: create packer dir
  file:
    path: /opt/packer-{{ version }}
    state: directory
    mode: 0755

- name: download packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ version }}/packer_{{ version }}_linux_amd64.zip
    dest: /opt/packer-{{ version }}
    remote_src: yes
    creates: /opt/packer-{{ version }}/packer

- name: install packer
  file:
    src: /opt/packer-{{ version }}/packer
    dest: /usr/local/bin/packer
    state: link
    
