- name: Install packer
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/packer/1.2.0/packer_1.2.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/packer
