- name: create terraform dir
  file:
    path: /opt/terraform-{{ version }}
    state: directory
    mode: 0755

- name: download terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip
    dest: /opt/terraform-{{ version }}
    remote_src: yes
    creates: /opt/terraform-{{ version }}/terraform

- name: install terraform
  file:
    src: /opt/terraform-{{ version }}/terraform
    dest: /usr/local/bin/terraform
    state: link
    
