- name: Uninstall vim-tiny
  become: yes
  apt:
    name: vim-tiny
    state: absent

- name: Install vim
  become: yes
  apt:
    name: vim

- name: Install vimrc config
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Set vim as default
  lineinfile:
    name: "~/.profile"
    regexp: "export VISUAL="
    line: "export VISUAL=vim"

- name: Set vim as default editor
  lineinfile:
    name: "~/.profile"
    regexp: "export EDITOR="
    line: "export EDITOR=$VISUAL"

