- name: Uninstall vim-tiny
  apt:
    name: vim-tiny
    state: absent

- name: Install vim
  apt:
    name: vim

- name: Install vimrc config
  become: no
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Set vim as default
  become: false
  lineinfile:
    name: "~/.profile"
    regexp: "export VISUAL="
    line: "export VISUAL=vim"

- name: Set vim as default editor
  become: false
  lineinfile:
    name: "~/.profile"
    regexp: "export EDITOR="
    line: "export EDITOR=$VISUAL"

